apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/dkrish194/argocd-metrics-demo.git
      targetRevision: main
      path: app-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
